name: nextline
description: App iOS de Nextline C,A

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  date_format: ^1.0.9
  basic_utils: ^2.6.0
  flutter_launcher_icons: ^0.7.5
  flutter_svg: ^0.19.3
  generic_bloc_provider: ^1.1.0
  firebase_messaging: ^7.0.0
  firebase_database: ^4.0.0
  firebase_storage: ^4.0.0
  firebase_core: ^0.5.0
  dio: ^3.0.10
  shared_preferences: ^0.5.8
  sqflite: ^1.3.1
  image_picker: ^0.6.7
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.30
  photo_view: ^0.10.1
  uuid: ^2.2.0
  email_validator: ^1.0.5
  workmanager: ^0.2.3
  url_launcher: ^5.7.2
  intl: ^0.15.6
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_dotenv: ^3.1.0

devÂº_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: "assets/images/imagotipo.png"
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: fontTitle
      fonts:
        - asset: fonts/TrebuchetBold.TTF
    - family: fontSubTitle
      fonts:
        - asset: fonts/TrebuchetRegular.TTF
    - family: fontInput
      fonts:
        - asset: fonts/SegoeUI.ttf
    - family: fontPoppinsBold
      fonts:
        - asset: fonts/PoppinsBold.ttf
    - family: fontPoppinsLight
      fonts:
        - asset: fonts/PoppinsLight.ttf
    - family: fontPoppinsRegular
      fonts:
        - asset: fonts/PoppinsRegular.ttf
    - family: fontPoppinsSemiBold
      fonts:
        - asset: fonts/PoppinsSemiBold.ttf

  assets:
    - .env
    - assets/images/fondo_login.png
    - assets/images/fondo_home.png
    - assets/images/fondo_app.png
    - assets/images/fondo_top_tickets.png
    - assets/images/imagotipo.png
    - assets/images/info.svg
    - assets/images/plus.svg
    - assets/images/logo_white.svg
    - assets/images/up-arrow.svg
    - assets/images/down-arrow.svg
    - assets/images/bg.jpg
    - assets/images/splash.jpg
    - assets/images/empresarial.svg
    - assets/images/dedicado.svg
    - assets/images/residencial.svg
    - assets/images/logo_without_text.svg
    - assets/images/icon_download.svg
    - assets/images/logomenu.jpg
    - assets/images/cambioplan.svg
    - assets/images/asistenciatecnica.svg
    - assets/images/cerrarsesion.svg
    - assets/images/facturacion.svg
    - assets/images/facturacion.png
    - assets/images/change_plan.png
    - assets/images/zelle.png
    - assets/images/bofa.png
    - assets/images/banesco.png
    - assets/images/paypal.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
